### ISSUE TITLE
Please add en-US fastlane for F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [billthefarmer/print#1]
Hi Bill, currently your app shows up without any summary and description at F-Droid – as your fastlane structure only has en-GB (so everyone coming with a different locale goes empty, as the fallback is en-US which is not present). Could you please add en-US, or rename en-GB to en-US? Thanks!

**Comment by billthefarmer** [comment]
This is two screenshots of the F-Droid app running in an emulator with the language set to de_DE and en_US.

![Screenshot_1628596537](https://user-images.githubusercontent.com/3448386/128862686-fa725428-3340-4b46-a7fa-4a37f8ddb562.png)

![Screenshot_1628596255](https://user-images.githubusercontent.com/3448386/128862742-d2b0b289-c97b-45e3-bae7-a01b5762ed61.png)

I made the mistake of writing the text description in HTML, which doesn't work at all well.

**Comment by IzzySoft** [comment]
HTML per se is fine – but as you just figured, you'd rather avoid "heading tags" (here: `<h2>`). Turn those into something like `<p><br><b>{title here}</b></p>` (the `<br>` only if any text came before) and do not leave empty lines inside your description (F-Droid converts each newline to `<br>\n`) and you are fine.

That you are seeing anything there is because the locale on your device is set to `en-GB`. Try with a device set to e.g. French, Spanish or German – you'll see nothing, as the `en-US` fallback is missing. I wonder why that seems to work for you: do you by chance have left `en-GB` as secondary language?

Please compare:

* https://apt.izzysoft.de/fdroid/index/apk/org.billthefarmer.print?repo=main

Just checked with https://f-droid.org/packages/org.billthefarmer.print/ and funnily it works there. Looks like someone has established a work-around to fallback to *any* `en*` if there's no `en-US`, despite of what specifications say – which leaves me to either shrug when that fails with my repo browser, or create a messy work-around violating the very same specs as well…

Thanks for checking, though – I wouldn't have noticed that change at all otherwise! And maybe my HTML hints helped you a bit as well. More detailed ones can be found [here in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) if you want to check for options.

**Comment by billthefarmer** [comment]
The fastlane data has worked fine for my apps since I put it up. I raised an issue about duplicate screenshots about two years ago https://gitlab.com/fdroid/fdroiddata/-/issues/1632. The emulator I used has only one language setting which changes the language for the whole device. It's easy to test the web site , you just change the URL from https://f-droid.org/en/packages/org.billthefarmer.print/ to https://f-droid.org/de/packages/org.billthefarmer.print/ or https://f-droid.org/fr/packages/org.billthefarmer.print/ and do a hard refresh Ctrl+F5.

![Screenshot_1628679658](https://user-images.githubusercontent.com/3448386/129018172-c8074482-dacb-499b-8e29-890d344eefa7.png)

**Comment by IzzySoft** [comment]
Bill, I won't complain. As it in fact seems that the official website and the Android client itself handle this fine, we could as well argue the papers (specs) are at fault – and I have to adjust it for my repo browser. Which I most likely will do, as your repo is certainly not the only one with a constellation like this. So if you want to keep it as-is on your end, I shall remember your app as a reference to test whether my implementation works :laughing:

Thanks for taking the time to investigate – and feel free to close this issue as "wontfix" :wink:

**Comment by IzzySoft** [comment]
PS: 5 lines of code fixed it on my end (not live yet, still testing/watching it for a little more) – so consider this part solved.

I see you already reworked the `full_description.txt` in Fastlane; have you considered skipping the first two lines, as they just duplicate the name shown right above anyway? The following should render fine:

```html
<i>Print</i> is a Print utility. To use, either open a document using the <b>Open</b> toolbar icon, or share a file or text in another app and choose the Print app in the popup dialog that appears.

In the toolbar you can…

* <b>Open</b> a document using the file manager
* <b>Print</b> the document, or write a pdf file
* <b>About</b> show the app copyright and version

<a href='https://en.wikipedia.org/wiki/Markdown' target='_blank'>Markdown</a> markup in the text will be parsed and rendered by the <a href='https://github.com/commonmark/commonmark-java' target='_blank' rel='nofollow'>commonmark</a> markdown library. URLs in the text will be turned into links so they may be followed.
```

**Comment by billthefarmer** [comment]
OK

**Comment by IzzySoft** [comment]
Now, don't you agree it looks better? :smile: I just checked to make sure, all worked out fine IMHO. Thanks once more!
