### ISSUE TITLE
checkbox in pdf file missing when printing

### ISSUE THREAD

**Issue by odmfl** [billthefarmer/print#10]
[antrag-auf-pflegeleistung-44100-data.pdf](https://github.com/billthefarmer/print/files/10883144/antrag-auf-pflegeleistung-44100-data.pdf)

the attached file contains checkboxes and forms, when printed they are not displayed.

**Comment by billthefarmer** [comment]
This app doesn't support pdf files. Use the Google PDF Viewer app. This app is impossible to find in the app store, but you can get it from [ApkPure](https://apkpure.com/google-pdf-viewer/com.google.android.apps.pdfviewer) and other sites.
