### ISSUE TITLE
Feature Request: disable Markdown conversion toggle

### ISSUE THREAD

**Issue by Mokura** [billthefarmer/print#3]
This app is an awesome piece of software I've not had for a while (print to PDF is something I hadn't had in FOSS in a while) but the ability to toggle off automatic Markdown proccessing would be nice.  If I'm printing plaintext to PDF it can cause issues, like unintentional Markdown formatting of ASCII art and the like.  Not a huge deal, but would be nice to have.  Thank you for your work.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by Mokura** [comment]
It works absolutely perfectly, thank you so much!

![Screenshot_20211123-175704_Print](https://user-images.githubusercontent.com/5167919/143142381-caf6116a-3cbc-4faf-8981-3a60b166c689.png)

![Screenshot_20211123-175801_Print_Spooler](https://user-images.githubusercontent.com/5167919/143142453-7d3bfc14-4820-405b-be2d-581fb6191c23.png)

![Screenshot_20211123-175846_Librera_PRO](https://user-images.githubusercontent.com/5167919/143142542-4578b048-2398-4856-a027-73b338c58bc1.png)
