### ISSUE TITLE
Share with to print app

### ISSUE THREAD

**Issue by yephny** [billthefarmer/print#4]
Would you consider adding support for all printable file formats? Currently, the app is used to view a text file and print it, though it'd be great if we could print .pdf and .png files too using this app (no need for previewing them).

My justification for this is that not all PDF readers, gallery apps, and file managers have the "Print" function, therefore creating a need for an app that you can share a file with to print it. This app seems to be a perfect candidate for this purpose as it is lightweight, can print, and is already present in the share menu (as long as the file extension is supported).

**Comment by billthefarmer** [comment]
I just checked this, both the gallery and the Google pdf viewer on both android 7 and 11 have a print function. This app uses the functionality which is part of the web view API for printing, which can handle HTML, text and markdown if enabled. This can handle images, if referenced by an HTML or markdown file, but not pdf.

**Comment by yephny** [comment]
I see, if breaking changes, or even an implementation of completely different APIs/libraries are required, then a new app should be a better candidate for this purpose. Thank you.
