### ISSUE TITLE
Add (print) a table possible ?

### ISSUE THREAD

**Issue by gbdomubpkm** [billthefarmer/print#5]
Hello.
Thank you very much for this app ! I like it very much, very usefull !
I tested several things using this link https://www.markdownguide.org/hacks/ that work in .txt file built with your awesome Editor app and then using print app,  and after, i tried to add a table using https://www.markdownguide.org/extended-syntax/#tables : it doesn't seem possible to get a table  (smartphone AOSP 10) with print app : Should this work ? I would like to be able to easily implement tables.
Regards

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

![Screenshot_20220515-101523 1](https://user-images.githubusercontent.com/3448386/168465765-c3408fb3-8002-4403-8f33-74e5b695f561.png)

**Comment by gbdomubpkm** [comment]
Thank you so much !  I also tested with your notes app, and that doesn't seem to work either. If your work isn't too different and can eventually later be implemented in the Notes app as well, that would be great. But thanks again.

**Comment by billthefarmer** [comment]
Notes has had tables and task lists since [version 1.13](https://github.com/billthefarmer/notes/releases/tag/v1.13).

**Comment by gbdomubpkm** [comment]
You're absolutely right, sorry. I had taken it badly for lack of habit. And in addition, I persisted in wanting to show the borders (framing) which cannot be done simply (I think) under markdown
