### ISSUE TITLE
Weird spacing of bullet lists

### ISSUE THREAD

**Issue by xandro0777** [billthefarmer/print#6]
Hi, I am using Quillnote and have several issues with spacing and line breaks. The first issue, following note

```
* xxxxcc
* xxxx
* Xxxx
* Xxxxc
* Xxxxc


* Xxxxcc

# xxx
* Xxxxc
* Xxxc
* Xxxcc
* xxcçxxc
* Xxxccc
* Xxcccc
* Xxxxccc
```

is printed oddly, the part before "#xxx" is printed with empty lines between each entry, the next part is printed as expected.

**Comment by billthefarmer** [comment]
All my apps use [CommonMark](https://commonmark.org) for markdown as there is a well supported [Java library](https://github.com/commonmark/commonmark-java) with lots of extensions. If you put your text above into [their gizmo](https://spec.commonmark.org/dingus)  you will see that it renders it exactly the same. If you look at the HTML you can see why, the first set of bullet points are wrapped in `p` tags. I know nothing of Quillnote.

**Comment by xandro0777** [comment]
I have Quillnote from F-Droid and didn't look if it uses some library.

Don't why html should matter here, looking at the markdown code the result is totally unexpected.

But if you think I should report the issues somewhere else I can do it, just don't know whose "fault" it is.

**Comment by billthefarmer** [comment]
So I looked it up. [Quillnote](https://github.com/msoultanidis/quillnote) uses [MarkWon](https://github.com/noties/Markwon), which uses Commonmark.

Using MarkWon is why Quillnote doesn't print.

It gets better &ndash; I submitted your text above to [BabelMark](https://babelmark.github.io/?text=*+xxxxcc%0A*+xxxx%0A*+Xxxx%0A*+Xxxxc%0A*+Xxxxc%0A%0A%0A*+Xxxxcc%0A%0A%23+xxx%0A*+Xxxxc%0A*+Xxxc%0A*+Xxxcc%0A*+xxc%C3%A7xxc%0A*+Xxxccc%0A*+Xxcccc%0A*+Xxxxccc) and most of the implementations tested produced the same result as Commonmark.

**Comment by xandro0777** [comment]
So why the differences... does one of the Apps use an old version of the library or some unusual settings?

**Comment by billthefarmer** [comment]
Markwon uses Commonmark to render markdown into a text view, bypassing HTML. Most markdown implementations render to HTML.

**Comment by xandro0777** [comment]
Ideally both should render the same. While I would understand subtle differences in spacing the bullet list rendering in "print" just looks wrong to me.

What also surprises is that apparently "print" doesn't understand ~~strikethrough~~?

**Comment by billthefarmer** [comment]
Underscore in an enhancement which isn't in 'standard' markdown. I have added several enhancements to my other apps that use markdown, but not so much this one because I haven't had much feedback compared with other apps. Probably because quite a few apps include printing, including mine.

**Comment by xandro0777** [comment]
I think the print App is a really great idea, like some other of your apps.

The Markdown thing starts looking like an an endless can of worms to me the more I learn about it though.

Isn't there some common minimum standard even for the simplest things? Neither a bullet list, nor linebreaks or strikethrough look like rocket science

**Comment by billthefarmer** [comment]
The original idea, AFAIK, is here &ndash; https://daringfireball.net/projects/markdown/basics. Things went uphill/downhill, possibly got sort of standardised from there. If you look at this &ndash; https://babelmark.github.io/?text=Test+%5Esup%5E+~sub~+~~strike~~+%2Bwhatever%2B+%2B%2Bunder%2B%2B+%60%5Esup%5E+~sub~%60%0A, you can see how many different implementations there are.

**Comment by xandro0777** [comment]
Just tried this one with the latest version from F-Droid and still have the problem?
